import React from 'react';
import Head from 'next/head';
import styles from '../styles/PostDetailLayout.module.css';

const PostDetailLayout = ({ children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>tech plazaa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <nav className={styles.nav}>
          <div className={styles.logo}>
            <img src="/w_logo.png" alt="Tech Plazaa Logo" />
          </div>
          <ul className={'d-flex list-unstyled gap-3 align-item-center justify-content-center'}>
            <li><a href="/">Home</a></li>
            <li><a href="/about">About</a></li>
            {/* Add more navigation links as needed */}
          </ul>
        </nav>
      </header>

      <main className={styles.mainContent}>{children}</main>

      <footer className={styles.footer}>
        <p>&copy; {new Date().getFullYear()} techPlazaa. All rights reserved.</p>
      </footer>
    </div>
  );
};

export default PostDetailLayout;
